// ICD-10-SE code strings as published in Socialstyrelsen's code list for medical alert information.
// Represented in a local CodeSystem so IG validation does not require international ICD-10 for national extensions.
Alias: $ICD10SE = http://hl7.se/fhir/r4/ig/medicalalertinformation/CodeSystem/SEAlertInformationICD10SECS

CodeSystem: SEAlertInformationICD10SECS
Id: SEAlertInformationICD10SECS
Title: "ICD-10-SE (medical alert information)"
Description: "ICD-10-SE diagnosis and status codes used in this implementation guide, with the same code strings as in Socialstyrelsen's code list."
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #"T78.3" "Angioneurotiskt ödem"
* #"T78.3" ^definition = "ICD-10-SE code string as published in Socialstyrelsen's national code list."
* #"I49.8E" "Långt QT-syndrom"
* #"I27.0" "Primär pulmonell hypertoni"
* #"I27.2" "Annan sekundär pulmonell hypertoni"
* #"E27.1" "Primär binjurebarksinsufficiens"
* #"T88.3" "Malign hypertermi orsakad av anestesi"
* #"D66.9" "Ärftlig brist på faktor VIII"
* #"D67.9" "Ärftlig brist på faktor IX"
* #"D68.0" "von Willebrands sjukdom"
* #"D68.1" "Hereditär brist på faktor XI"
* #"D68.2" "Hereditär brist på andra koagulationsfaktorer"
* #"D68.3" "Hemorragisk sjukdom orsakad av cirkulerande antikoagulantia"
* #"D68.4" "Förvärvad brist på koagulationsfaktor"
* #"D68.5" "Primär trombofili"
* #"D68.6" "Annan trombofili"
* #"D68.8" "Andra specificerade koagulationsrubbningar"
* #"D68.9" "Koagulationsrubbning, ospecificerad"
* #"D69.0" "Allergisk purpura"
* #"D69.1" "Kvalitativa trombocytdefekter"
* #"D69.3" "Idiopatisk trombocytopen purpura"
* #"D69.4" "Annan primär trombocytopeni"
* #"D69.5" "Sekundär trombocytopeni"
* #"D69.6" "Trombocytopeni, ospecificerad"
* #"M31.1" "Trombotisk mikroangiopati"
* #"G70.0" "Myasthenia gravis"
* #"E80.2A" "Akut intermittent porfyri (hepatisk)"
* #"E80.2D" "Porphyria variegata"
* #"E80.2B" "Hereditär koproporfyri"
* #"E80.2W" "Annan specificerad porfyri"
* #"E88.0" "Rubbningar i plasmaproteinomsättningen som ej klassificeras på annan plats"
* #"E88.0W" "Annan specificerad rubbning i plasmaproteinomsättningen som ej klassificeras på annan plats"
* #"T88.2" "Chock orsakad av anestesi"
* #"T88.5" "Andra komplikationer till anestesi"
* #"T88.4" "Misslyckad eller försvårad intubation"
* #"D73.0" "Hyposplenism"
* #"Q89.0" "Medfödda missbildningar av mjälten"
* #"D81" "Kombinerade immunbristtillstånd"
* #"D70.9A" "Agranulocytos"
* #"D70.9B" "Kostmanns sjukdom"
* #"D70.9D" "Shwachmans syndrom"
* #"D71.9" "Funktionella rubbningar hos polymorfkärniga neutrofila celler (vissa vita blodkroppar)"
* #"I77.0" "Arteriovenös fistel, förvärvad"
* #"E71.0" "E71.0"
* #"E71.2" "E71.2"
* #"E71.3" "E71.3"
* #"E71.1A" "E71.1A"
* #"E71.1B" "E71.1B"
* #"E71.1C" "E71.1C"
* #"E71.1D" "E71.1D"
* #"E71.3A" "E71.3A"
* #"E71.3B" "E71.3B"
* #"E71.3C" "E71.3C"
* #"E72.2" "E72.2"
* #"E72.3" "E72.3"
* #"E72.2B" "E72.2B"
* #"E72.2C" "E72.2C"
* #"E74.0" "E74.0"
* #"E74.1" "E74.1"
* #"E74.4" "E74.4"
* #"E88.9" "E88.9"
* #"E79.8" "E79.8"
* #"G71.3" "G71.3"
* #"E25.0" "E25.0"
* #"K52.2" "K52.2"
* #"Z95.0" "Förekomst av elektronisk kardiell anordning"
* #"Z95.2" "Förekomst av hjärtklaffprotes av icke-biologiskt material"
* #"Z95.4" "Förekomst av annan typ av hjärtklaffsersättning"
* #"Z98.2" "Tillstånd med förekomst av hjälpmedel för dränage av cerebrospinalvätska"
* #"Z96.0" "Artificiell uretrasfinkter"
* #"Z96.2" "Cochleaimplantat"
* #"Z96.8" "Förekomst av annat specificerat implantat"
* #"Z99.4" "Hjärtpump för vänster kammare"
* #"Z94.0" "Njurtransplanterad"
* #"Z94.1" "Hjärttransplanterad"
* #"Z94.2" "Lungtransplanterad"
* #"Z94.4" "Levertransplanterad"
* #"Z94.8" "Andra specificerade transplantationstillstand"
* #"Z79.89" "Långtidsanvändning av andra specificerade läkemedel"
* #"Z92.1" "Långtidsanvändning (och pågående användning) av blodförtunnande medel i den egna sjukhistorien"
* #"Z99.2" "Beroende av njurdialys"
* #"A49.9" "Bakteriell infektion, ospecificerad"
