CodeSystem: SEAlertLabelCS
Id: SEAlertLabelCS
Title: "SE Alert Labels"
Description: "Alert labels shown per alert, aligned with the national code list published by Socialstyrelsen."
* ^experimental = false
* ^caseSensitive = true
* #angioneurotiskt-odem "Angioneurotiskt ödem"
* #angioneurotiskt-odem ^definition = "User-facing alert label aligned with the national code list (Socialstyrelsen)."
* #langt-qt-syndrom-lqts "Långt QT-syndrom (LQTS)"
* #pulmonell-hypertension "Pulmonell hypertension"
* #addisons-sjukdom "Addisons sjukdom"
* #malign-hypertermikanslighet "Malign hypertermikänslighet"
* #koagulationsrubbningar "Koagulationsrubbningar"
* #trombocytrelaterad-sjukdom-med-okad-blodningstendens "Trombocytrelaterad sjukdom med ökad blödningstendens"
* #trombofili "Trombofili"
* #myasthenia-gravis "Myasthenia gravis"
* #akut-intermittent-porfyri "Akut intermittent porfyri"
* #porfyria-variegata "Porfyria variegata"
* #hereditar-koproporfyri "Hereditär koproporfyri"
* #alad-bristporfyri "ALAD-bristporfyri"
* #pseudokolinesterasbrist "Pseudokolinesterasbrist"
* #anestesiproblem "Anestesiproblem"
* #svarintuberad "Svårintuberad"
* #aspleni "Aspleni"
* #svar-kombinerad-immunbrist-scid "Svår kombinerad immunbrist (SCID)"
* #agranulocytos "Agranulocytos"
* #kostmanns-sjukdom "Kostmanns sjukdom"
* #shwachmans-syndrom "Shwachmans syndrom"
* #storning-av-neutrofilfunktion "Störning av neutrofilfunktion"
* #anlagd-av-fistel "Anlagd AV-fistel"
* #maple-syrup-urine-disease-msud "Maple-syrup-urine disease [MSUD]"
* #rubbning-i-omsattningen-av-grenade-aminosyror-ospecificerad "Rubbning i omsättningen av grenade aminosyror, ospecificerad"
* #rubbningar-i-fettsyraomsattningen "Rubbningar i fettsyraomsättningen"
* #hyperleucin-isoleucinemi "Hyperleucin-isoleucinemi"
* #isovalerisk-acidemi "Isovalerisk acidemi"
* #metylmalonisk-acidemi "Metylmalonisk acidemi"
* #propionisk-acidemi "Propionisk acidemi"
* #karnitincykel-transportdefekter "Karnitincykel/transportdefekter"
* #betaoxidationsrubbningar "Betaoxidationsrubbningar"
* #acyl-co-enzym-a-dehydrogenas-brist "Acyl-co-enzym A-dehydrogenas-brist"
* #rubbningar-i-urinamnesomsattningen "Rubbningar i urinämnesomsättningen"
* #rubbningar-i-lysin-och-hydroxylysinomsattningen "Rubbningar i lysin- och hydroxylysinomsättningen"
* #arginobarnstenssyruri "Arginobärnstenssyruri"
* #citrullinemi "Citrullinemi"
* #glykogeninlagringssjukdom "Glykogeninlagringssjukdom"
* #rubbningar-i-fruktosomsattningen "Rubbningar i fruktosomsättningen"
* #rubbningar-i-pyruvatomsattning-och-glukoneogenes "Rubbningar i pyruvatomsättning och glukoneogenes"
* #amnesomsattningssjukdom-ospecificerad "Ämnesomsättningssjukdom, ospecificerad"
* #andra-specificerade-rubbningar-i-purin-och-pyrimidinomsattningen "Andra specificerade rubbningar i purin- och pyrimidinomsättningen"
* #mitokondriell-myopati-som-ej-klassificeras-pa-annan-plats "Mitokondriell myopati som ej klassificeras på annan plats"
* #kongenital-binjurebarkshyperplasi-cah "Kongenital binjurebarkshyperplasi (CAH)"
* #food-protein-induced-enterocolitis-syndrome-fpies "Food protein induced enterocolitis syndrome (FPIES)"
* #anlagt-av-graft "Anlagt AV-graft"
* #behandling-atc-1-2-752-116-3-1-16-1-2-2 "Behandling ATC (1.2.752.116.3.1.16.1.2.2)"
* #antikoagulantiabehandling "Antikoagulantiabehandling"
* #warfarinbehandling "Warfarinbehandling"
* #cytostatikabehandling "Cytostatikabehandling"
* #immunmodulerande-behandling "Immunmodulerande behandling"
* #beroende-av-icke-invasiv-ventilation "Beroende av icke-invasiv ventilation"
* #dialysbehandling "Dialysbehandling"
* #implanterbar-defibrillator-icd-implantable-cardioverter-defibrillator "Implanterbar defibrillator (ICD – implantable cardioverter-defibrillator)"
* #pacemaker "Pacemaker"
* #mekanisk-hjartklaffprotes "Mekanisk hjärtklaffprotes"
* #intrakraniella-coils "Intrakraniella coils"
* #intrakraniella-vaskulara-clips "Intrakraniella vaskulära clips"
* #intrakraniella-magnetiska-metaller "Intrakraniella magnetiska metaller"
* #shunt-i-centrala-nervsystemet "Shunt i centrala nervsystemet"
* #trakealstent "Trakealstent"
* #insulinpump "Insulinpump"
* #artificiell-uretrasfinkter "Artificiell Uretrasfinkter"
* #cochleaimplantat "Cochleaimplantat"
* #neurostimulator-i-centrala-nervsystemet "Neurostimulator i centrala nervsystemet"
* #vagusnervstimulator "Vagusnervstimulator"
* #frenikusstimulator-diafragmal-pacemaker "Frenikusstimulator/diafragmal pacemaker"
* #hjartpump-for-vanster-kammare "Hjärtpump för vänster kammare"
* #pacemakerelektrod "Pacemakerelektrod"
* #stamcellstransplanterad "Stamcellstransplanterad"
* #hjarttransplanterad "Hjärttransplanterad"
* #levertransplanterad "Levertransplanterad"
* #lungtransplanterad "Lungtransplanterad"
* #njurtransplanterad "Njurtransplanterad"
* #pankreastransplanterad "Pankreastransplanterad"
* #tarmtransplanterad "Tarmtransplanterad"
* #mrsa-meticillinresistenta-staphylococcus-aureus "MRSA (meticillinresistenta Staphylococcus aureus)"
* #vre-vankomycinresistenta-enterokocker "VRE (vankomycinresistenta enterokocker)"
* #tarmbakterier-som-bildar-esbl-extended-spectrum-beta-lactamase "Tarmbakterier som bildar ESBL (Extended Spectrum Beta-Lactamase)"
* #tarmbakterier-som-bildar-esbl-carba "Tarmbakterier som bildar ESBL CARBA"
* #blodsmitta-hos-gravid "Blodsmitta hos gravid"
* #allvarlig-arytmi "Allvarlig arytmi"
* #anafylaktisk-reaktion "Anafylaktisk reaktion"
* #angioodem "Angioödem"
* #astma "Astma"
* #blodtrycksfall "Blodtrycksfall"
* #forvirring "Förvirring"
* #generaliserade-kramper "Generaliserade kramper"
* #larynxodem "Larynxödem"
* #stevens-johnsons-syndrom "Stevens-Johnsons syndrom"
* #svar-urtikaria "Svår urtikaria"
* #sankt-medvetandegrad "Sänkt medvetandegrad"
* #toxisk-epidermal-nekrolys "Toxisk epidermal nekrolys"
* #annat "Annat"
* #diarre "Diarré"
* #hudrodnad "Hudrodnad"
* #hudsvullnad "Hudsvullnad"
* #klada "Klåda"
* #krakningar "Kräkningar"
* #lindrig-till-medelsvar-urtikaria "Lindrig till medelsvår urtikaria"
* #irritation-i-mun-och-svalg "Irritation i mun och svalg"
* #irritation-i-nasa "Irritation i näsa"
* #irritation-i-ogon "Irritation i ögon"
* #tungandning "Tungandning"
* #klorhexidin "Klorhexidin"
* #latex "Latex"
* #taurolidin "Taurolidin"
* #hotbild-mot-patient "Hotbild mot patient"
* #deltagare-i-klinisk-lakemedelsprovning "Deltagare i klinisk läkemedelsprövning"
* #deltagare-i-klinisk-provning "Deltagare i klinisk prövning"
* #patienten-accepterar-ej-blod-eller-plasmatransfusion "Patienten accepterar ej blod- eller plasmatransfusion"
* #patienten-accepterar-ej-autolog-blodtransfusion-eller-cellsaver "Patienten accepterar ej autolog blodtransfusion eller cellsaver"
* #lakarbeslut-finns-om-att-inte-utfora-hjart-lungraddning "Läkarbeslut finns om att inte utföra hjärt-lungräddning"
* #lakarbeslut-finns-om-att-avsluta-livsuppehallande-behandling "Läkarbeslut finns om att avsluta livsuppehållande behandling"
* #lakarbeslut-finns-fran-brytpunktssamtal "Läkarbeslut finns från brytpunktssamtal"
* #forskrivningsrestriktioner "Förskrivningsrestriktioner"
* #hanvisning-finns-till-en-specifik-vardenhet "Hänvisning finns till en specifik vårdenhet"
* #lakemedelsprodukt "Läkemedelsprodukt"
* #ej-strukturanpassad-uppmarksamhetsinformation "Ej strukturanpassad uppmärksamhetsinformation"

ValueSet: SEAlertLabelVS
Id: SEAlertLabelVS
Title: "SE Alert Labels"
Description: "Alert labels displayed per alert."
* ^experimental = false
* include codes from system SEAlertLabelCS
